=== Barca88/PRI2020/TPC-2/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT projectRecord ( title, data, team, abstract, deliverables) >
<!ELEMENT title (#PCDATA) >

<!ELEMENT data (title, subtitle*, beginDate, endDate, supervisor) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT beginDate (#PCDATA) >
<!ELEMENT endDate (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >
<!ATTLIST supervisor
            href CDATA #REQUIRED>

<!ELEMENT team (element+) >
<!ELEMENT element (name, number, email) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT number (#PCDATA) >
<!ELEMENT email (#PCDATA) >

<!ELEMENT abstract (paragraph+) >

<!ELEMENT paragraph (line+) >
<!ELEMENT line (#PCDATA|i|b|u|ref)* >
<!ELEMENT i (#PCDATA|b|u|ref)* >
<!ELEMENT b (#PCDATA|i|u|ref)* >
<!ELEMENT u (#PCDATA|i|b|ref)* >

<!ELEMENT deliverables (ref+) >
<!ELEMENT ref (#PCDATA) >
<!ATTLIST ref
            url CDATA #REQUIRED >

=== Barca88/PRI2020/TPC-8/tpc8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectRecord SYSTEM "../TPC-2/PR.dtd">
<projectRecord>
    <title>TPC 8</title>
    <data>
        <title>TPC 8</title>
        <subtitle>Servidor js a fazer download e upload de vários ficheiros</subtitle>
        <beginDate>4/12/2020</beginDate>
        <endDate>5/12/2020</endDate>
        <supervisor href="https://www.di.uminho.pt/~jcr">Professor JCR</supervisor>
    </data>
    <team>
        <element>
            <name>Marco Matias Pereira Gonçalves</name>
            <number>a75480</number>
            <email>marcomatiaspg@gmail.com</email>
        </element>
    </team>
    <abstract>
        <paragraph>
            <line>No ficheiro <i>html-templates</i> temos o código para gerar o código html </line>
            <line>No ficheiro <i>server.js</i> temos o código do servidor que trata os GET's e os POST's </line>
            <line>Na pasta <i>public</i> temos o código que é corrido no lado utilizador como o <b>form.js</b> e o <b>imagens.js</b> e o CSS bem como o código jquerry<line>
        </paragraph>
        <paragraph>
            <line>Para correr basta '$ npm install' seguido de um '$ npm start' caso não funcione poderá ter que instalar o package <b>nodemon</b></line>
        </paragraph>   
    </abstract>
    <deliverables>
        <ref href="./server.js">Servidor</ref>
        <ref href="./html-templates">Funcoes que geram código html</ref>
        <ref href="./public/form.js">Cógido a ser executado no clente</ref>
        <ref href="./public/imagens.js">Cógido a ser executado no clente</ref>
    </deliverables>
</projectRecord>

=== Barca88/PRI2020/TPC-2/TP2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectRecord SYSTEM "PR.dtd">
<projectRecord>
    <title>TPC 2</title>
    <data>
        <title>TPC 2</title>
        <subtitle>DTD do Project Recorder</subtitle>
        <subtitle>Queries de Xpath sobre arq.xml</subtitle>
        <beginDate>25/10/2020</beginDate>
        <endDate>26/10/2020</endDate>
        <supervisor href=""></supervisor>
    </data>
    <team>
        <element>
            <name>Marco Matias Pereira Gon√ßalves</name>
            <number>a75480</number>
            <email>marcomatiaspg@gmail.com</email>
        </element>
    </team>
    <abstract>
        <paragraph>
            <line>O DTD <bold>respeita</bold> os <italic>parametros</italic> <underlined>pedidos</underlined>.</line>
        </paragraph>
        <paragraph>
            <line></line>
        </paragraph>
    </abstract>
    <deliverables>
        <ref href="./PR.dtd">DTD</ref>
        <ref href="./queries.txt">Queries</ref>
    </deliverables>
</projectRecord>

=== Barca88/PRI2020/TPC-6/tpc6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectRecord SYSTEM "../TPC-2/PR.dtd">
<projectRecord>
    <title>TPC 6</title>
    <data>
        <title>TPC 6</title>
        <subtitle>To do List em Single page</subtitle>
        <beginDate>21/11/2020</beginDate>
        <endDate>23/11/2020</endDate>
        <supervisor href="https://www.di.uminho.pt/~jcr">Professor JCR</supervisor>
    </data>
    <team>
        <element>
            <name>Marco Matias Pereira Gonçalves</name>
            <number>a75480</number>
            <email>marcomatiaspg@gmail.com</email>
        </element>
    </team>
    <abstract>
        <paragraph>
            <line>Correndo 'json-server db.json' e noutro termial 'node toDoList.js' já consegue gerir as suas tarefas <ref href="http://localhost:8888/">na porta 8888</ref></line>
            <line>Quanto aos responsaveis é necessário povoar a base de dados á mão caso queria acrescentar algum.</line>
        </paragraph>
    </abstract>
    <deliverables>
        <ref href="./toDoList.js">Servidor da ToDo List</ref>
        <ref href="./db.json">Base de dados</ref>
    </deliverables>
</projectRecord>

=== Barca88/PRI2020/TPC-5/tpc5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectRecord SYSTEM "../TPC-2/PR.dtd">
<projectRecord>
    <title>TPC 5</title>
    <data>
        <title>TPC 5</title>
        <subtitle>Servidor node sobre elementos da escola de musica</subtitle>
        <beginDate>8/11/2020</beginDate>
        <endDate>15/11/2020</endDate>
        <supervisor href="https://www.di.uminho.pt/~jcr">Professor JCR</supervisor>
    </data>
    <team>
        <element>
            <name>Marco Matias Pereira Gonçalves</name>
            <number>a75480</number>
            <email>marcomatiaspg@gmail.com</email>
        </element>
    </team>
    <abstract>
        <paragraph>
            <line>Correndo 'node escola.js' o Servidor é iniciado conseguindo assim correr o <i> webservice </i> pedido com <ref url="http://localhost:3001/">este url</ref></line>
            <line>Com o servidor a correr este precisa de ir buscar os dados á base de dados e para isso utiliza o json-server.</line>
            <line>Para o correr precisamos apenas de correr 'json-server db.js' e ficamos com a <ref url="http://localhost:3001/">base de dados</ref> do db.json fornecido pelo professor e actualizado por mim.</line>
        </paragraph>
    </abstract>
    <deliverables>
        <ref href="./escola.js">Servidor</ref>
        <ref href="./db.json">Base de dados</ref>
    </deliverables>
</projectRecord>

=== Barca88/PRI2020/TPC-4/tpc3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectRecord SYSTEM "../TPC-2/PR.dtd">
<projectRecord>
    <title>TPC 3</title>
    <data>
        <title>TPC 3</title>
        <subtitle>Servidor js a ler html</subtitle>
        <beginDate>8/11/2020</beginDate>
        <endDate>9/11/2020</endDate>
        <supervisor href="https://www.di.uminho.pt/~jcr">Professor JCR</supervisor>
    </data>
    <team>
        <element>
            <name>Marco Matias Pereira Gonçalves</name>
            <number>a75480</number>
            <email>marcomatiaspg@gmail.com</email>
        </element>
    </team>
    <abstract>
        <paragraph>
            <line>Correndo 'node server.js' o Servidor é iniciado conseguindo assim correr o <i> webservice </i> pedido com o <ref url="http://localhost:7777/">este url</line>
        </paragraph>
    </abstract>
    <deliverables>
        <ref href="./server.js">Servidor</ref>
        <ref href="./multi_indice.xsl">XSL usado</ref>
        <ref href="./arq(1).xml">XML fornecido</ref>
        <ref href="http://localhost:7777/">Webservice</ref>
    </deliverables>
</projectRecord>
